version: '3'
services:
  # Spring Boot Application
  spring-app:
    image: your-spring-app-image:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/yourdb
      - SPRING_DATASOURCE_USERNAME=yourusername
      - SPRING_DATASOURCE_PASSWORD=yourpassword
    depends_on:
      - mysql-db

  # MySQL Database
  mysql-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=yourdb
      - MYSQL_USER=yourusername
      - MYSQL_PASSWORD=yourpassword
    ports:
      - "3306:3306"
